apiVersion: search.open-cluster-management.io/v1alpha1
kind: Search
metadata:
  name: search-v2-operator
  namespace: open-cluster-management
  annotations:
    # Ensure ArgoCD can apply this over the operator-generated defaults
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  dbStorage:
    size: 10Gi
    storageClassName: ocs-storagecluster-ceph-rbd